### ISSUE TITLE
Please port minecraft 1.20.6

### ISSUE THREAD

**Issue by BAD7777** [PretzelJohn/VillagerTradeLimiter#12]
Please port minecraft 1.20.6

**Comment by BAD7777** [comment]
Could not pass event InventoryCloseEvent to VillagerTradeLimiter v1.6.5
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at VillagerTradeLimiter-1.6.5.jar/com.pretzel.dev.villagertradelimiter.nms.utils.MinecraftVersion.getVersion(MinecraftVersion.java:111) ~[VillagerTradeLimiter-1.6.5.jar:?]
	at VillagerTradeLimiter-1.6.5.jar/com.pretzel.dev.villagertradelimiter.nms.NBTCompound.getType(NBTCompound.java:1342) ~[VillagerTradeLimiter-1.6.5.jar:?]
	at VillagerTradeLimiter-1.6.5.jar/com.pretzel.dev.villagertradelimiter.nms.NBTCompound.getCompound(NBTCompound.java:786) ~[VillagerTradeLimiter-1.6.5.jar:?]
	at VillagerTradeLimiter-1.6.5.jar/com.pretzel.dev.villagertradelimiter.wrappers.VillagerWrapper.getRecipes(VillagerWrapper.java:35) ~[VillagerTradeLimiter-1.6.5.jar:?]
	at VillagerTradeLimiter-1.6.5.jar/com.pretzel.dev.villagertradelimiter.wrappers.VillagerWrapper.reset(VillagerWrapper.java:83) ~[VillagerTradeLimiter-1.6.5.jar:?]
	at VillagerTradeLimiter-1.6.5.jar/com.pretzel.dev.villagertradelimiter.listeners.InventoryListener.onPlayerStopTrading(InventoryListener.java:73) ~[VillagerTradeLimiter-1.6.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor722.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2227-79d199c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1631) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3012) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3005) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by CloudeLecaw** [comment]
https://github.com/PretzelJohn/VillagerTradeLimiter/issues/13

I think this can be combined to the thread for 1.21 support to
support for 1.20.5 to 1.21.1

**Comment by tapochkov** [comment]
Already added support for 1.20.6?
